# Generated by Django 4.2.2 on 2023-09-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "promoter",
            "0008_promoter_street_address_squashed_0009_promoter_country_code_promoter_postal_zip_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="promoter",
            name="address",
            field=models.TextField(default=""),
        ),
    ]
