# Generated by Django 4.2.2 on 2023-09-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promoters", "0006_promoter_birth_squashed_0007_promoter_death"),
    ]

    operations = [
        migrations.AddField(
            model_name="promoter",
            name="street_address",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
    ]
