# Generated by Django 5.0a1 on 2023-10-10 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promoters", "0011_data_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promoter",
            name="city",
        ),
        migrations.RemoveField(
            model_name="promoter",
            name="country_code",
        ),
        migrations.RemoveField(
            model_name="promoter",
            name="postal_zip",
        ),
        migrations.RemoveField(
            model_name="promoter",
            name="province_state",
        ),
        migrations.RemoveField(
            model_name="promoter",
            name="street_address",
        ),
    ]
