# Generated by Django 5.0a1 on 2023-10-31 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_seekingad_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeekingAd",
        ),
    ]
