# Generated by Django 5.0b1 on 2023-11-09 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_seekingad_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeekingAd",
        ),
    ]
