# Generated by Django 4.1.5 on 2023-04-24 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bands", "0003_band"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="band",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="musician",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "musician_profiles",
                    models.ManyToManyField(to="bands.musician"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("venues_controlled", models.ManyToManyField(to="bands.venue")),
            ],
        ),
    ]
