# Generated by Django 5.0.1 on 2024-02-11 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0003_band"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="musician",
            options={"ordering": ["last_name", "first_name"]},
        ),
    ]
