# Generated by Django 4.1.5 on 2023-05-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0006_venue_description_venue_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="musician",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
