# Generated by Django 4.2.2 on 2023-09-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promoter", "0008_promoter_street_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="promoter",
            name="city",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promoter",
            name="country_code",
            field=models.CharField(default="", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promoter",
            name="postal_zip",
            field=models.CharField(default="", max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promoter",
            name="province_state",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
    ]
